In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import preprocessing
df=pd.read_csv('iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [2]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [4]:
X=df.iloc[:,1:5]
Y=df.iloc[:,-1]

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_test,x_train,y_test,y_train=train_test_split(X,Y,test_size=0.33,random_state=False)

In [7]:
scaler=preprocessing.StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [8]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [9]:
model.score(x_test,y_test)

0.96

In [10]:
y_pred=model.predict(x_test)

In [11]:
print(y_test,y_pred)

69     Iris-versicolor
135     Iris-virginica
56     Iris-versicolor
80     Iris-versicolor
123     Iris-virginica
            ...       
9          Iris-setosa
103     Iris-virginica
67     Iris-versicolor
117     Iris-virginica
47         Iris-setosa
Name: Species, Length: 100, dtype: object ['Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-setos

In [12]:
model.score(x_test,y_pred)

1.0

In [14]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [15]:
print(accuracy_score(y_test,y_pred))

0.96


In [16]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[34  0  0]
 [ 0 30  1]
 [ 0  3 32]]


In [17]:
#iris-setosa
tp=cm[0][0]
fn=cm[0][1]+cm[0][2]
fp=cm[1][0]+cm[2][0]
tn=cm[1][1]+cm[1][2]+cm[2][1]+cm[2][2]
total=tp+fp+fn+tn

In [22]:
accuracy=(tp+tn)/total
error_rate=(fp+fn)/total
recall=tp/tp+fn
precision=tp/tp+fp

In [23]:
print(accuracy)
print(error_rate)
print(recall)
print(precision)

1.0
0.0
1.0
1.0


In [24]:
#same for other two

class_repo = classification_report(y_test,y_pred)
print(class_repo)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        34
Iris-versicolor       0.91      0.97      0.94        31
 Iris-virginica       0.97      0.91      0.94        35

       accuracy                           0.96       100
      macro avg       0.96      0.96      0.96       100
   weighted avg       0.96      0.96      0.96       100

